### ISSUE TITLE
Set initial ESS states / Set previous timestep values

### ISSUE THREAD

**Issue by ahilloffis** [mtress/mtress#18]
To use MTRESS as control algorithm in a continuous setting, I need a way to initially set the states of the used ESS.

Alternatively it could also be a good idea to be able to set values of past timestep(s) as initialization for the whole system. This would help using MTRESS in a model predictive control fashion.

**Comment by p-snft** [comment]
This is easy for batteries, as their SOC is routinely abstracted to a single value (percentage). For heat storages, a translation from temperature readings to storage levels (maybe one per temperature level) has to be defined. Thus, I started with the battery. If this is already enough, I'd merge that change and make a pip release.

**Comment by ahilloffis** [comment]
It would be enough for the moment but as soon as we also use heat storage we need that too for our simulation.
And we plan to us a heat storage as soon as possible. I think it is up to you to decide which way is better for you.

**Comment by p-snft** [comment]
Would you test https://pypi.org/project/mtress/2.2.0rc1/?

Definition of the initial contents is in https://github.com/mtress/mtress/blob/release/v2/example/all_techs_example.yaml,
API to get the results is like:

```Python
meta_model.storage_contents(meta_model.battery_content)
meta_model.storage_contents(meta_model.th_storage_content)
```
