### ISSUE TITLE
Temperature is converted to Kelvin twice

### ISSUE THREAD

**Issue by flpeters** [mtress/mtress#27]
Hi, as someone who just stumbled onto your project and took a look at the code,
I've noticed that the function `calc_isothermal_compression_energy` in `physics/_helper_functions.py` converts the incoming temperature to Kelvin twice in a row [here](https://github.com/mtress/mtress/blob/7892bb4fbcd0b4f568de3adc8088a3344176a04a/mtress/physics/_helper_functions.py#L138).
Hope this helps and I didn't misunderstand anything.

**Comment by p-snft** [comment]
Thanks for telling. I just fixed the problem.
